- hosts: web
  become: yes
  tasks:
    - name: Docker eklentilerini kontrol et
      apt:
        name: docker-compose-v2
        state: present
        update_cache: yes

    - name: Mevcut sistemi durdur
      shell: "cd /home/ubuntu/project && docker compose down || true"

    - name: Dosyalari kopyala
      copy:
        src: ../
        dest: /home/ubuntu/project/

    - name: MHRS Backend Build
      shell: "cd /home/ubuntu/project && docker compose build backend"

    - name: MHRS Frontend Build
      shell: "cd /home/ubuntu/project && docker compose build frontend"

    - name: MHRS Sistemini Baslat
      shell: "cd /home/ubuntu/project && docker compose up -d"