- hosts: web
  become: yes
  tasks:
    - name: Docker Compose yuklu mu kontrol et ve yukle
      apt:
        name: docker-compose
        state: present
        update_cache: yes

    - name: Mevcut konteynerlari durdur ve temizle
      shell: "docker-compose -f /home/ubuntu/project/docker-compose.yml down --remove-orphans || true"

    - name: Proje klasörünü temizle
      file:
        path: /home/ubuntu/project
        state: absent

    - name: Proje klasörünü yeniden oluştur
      file:
        path: /home/ubuntu/project
        state: directory
        mode: '0755'

    - name: Dosyaları kopyala
      copy:
        src: ../
        dest: /home/ubuntu/project/

    - name: MHRS Sistemini Başlat
      shell: "cd /home/ubuntu/project && docker-compose up -d --build"