- hosts: web
  become: yes
  tasks:
    - name: Docker Compose yüklü mü kontrol et
      apt:
        name: docker-compose
        state: present

    - name: Eski konteynerları durdur
      shell: "docker-compose -f /home/ubuntu/project/docker-compose.yml down || true"

    - name: Proje klasörünü temizle ve oluştur
      file:
        path: /home/ubuntu/project
        state: directory
        mode: '0755'

    - name: Dosyaları sunucuya kopyala
      copy:
        src: ../
        dest: /home/ubuntu/project/

    - name: Docker Compose ile MHRS'yi ayağa kaldır
      shell: "cd /home/ubuntu/project && docker-compose up -d --build"