name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Repo çek
      uses: actions/checkout@v3

    - name: SSH key ekle
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy (Ansible)
      run: |
        ansible-playbook -i ansible/inventory.ini ansible/deploy.yml \
        --private-key ~/.ssh/id_rsa \
        --ssh-common-args='-o StrictHostKeyChecking=no'